// Generated by CoffeeScript 1.3.3
var ArrayQuery, Reader, fs;

fs = require("fs");

ArrayQuery = require("./array-query");

Reader = (function() {

  function Reader(dataPath) {
    this.dataPath = dataPath;
    if (!fs.existsSync(this.dataPath)) {
      fs.mkdirSync(this.dataPath, "757");
    }
  }

  Reader.prototype.get = function() {
    var files, list,
      _this = this;
    files = fs.readdirSync(this.dataPath);
    list = [];
    files.forEach(function(fileName) {
      var data, file;
      file = fs.readFileSync(_this.dataPath + fileName) + "";
      if (file) {
        try {
          data = JSON.parse(file);
          if (data) {
            return list.push(data);
          }
        } catch (e) {
          return console.log(e);
        }
      }
    });
    return new ArrayQuery(list);
  };

  return Reader;

})();

module.exports = Reader;
