// Generated by CoffeeScript 1.3.3
var Calendar, Reader, Rest, fs,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

fs = require("fs");

Rest = require("./rest");

Reader = require("../helpers/reader");

Calendar = (function(_super) {

  __extends(Calendar, _super);

  function Calendar(appConfig) {
    this.getScheduleName = __bind(this.getScheduleName, this);

    this.makePath = __bind(this.makePath, this);

    this.writeData = __bind(this.writeData, this);

    this["delete"] = __bind(this["delete"], this);

    this.put = __bind(this.put, this);

    this.get = __bind(this.get, this);

    this.post = __bind(this.post, this);
    Calendar.__super__.constructor.call(this, "calendar", appConfig);
  }

  Calendar.prototype.post = function(req, res) {
    var data, fileName;
    data = req.body;
    fileName = this.makePath(data);
    return this.writeData(data, res, fileName);
  };

  Calendar.prototype.get = function(req, res) {
    var _this = this;
    return res.format({
      json: function() {
        return res.send(_this.reader.get().all());
      },
      html: function() {
        return res.render(_this.name, {
          title: _this.appConfig.name
        });
      }
    });
  };

  Calendar.prototype.put = function(req, res) {
    var data, fileName;
    data = req.body;
    data.allDay = data.allDay === "true";
    fileName = this.makePath(data);
    fs.unlinkSync(fileName);
    return this.writeData(data, res, fileName);
  };

  Calendar.prototype["delete"] = function(req, res) {
    var data;
    data = req.body;
    console.log("delete:" + data._id);
    data = req.body;
    return fs.unlink(this.makePath(data), function(err) {
      if (err) {
        return res.send(500, "Can't Delete");
      } else {
        return res.send(200, "Deleted");
      }
    });
  };

  Calendar.prototype.writeData = function(data, res, fileName) {
    var _this = this;
    if (!fs.existsSync(fileName)) {
      return fs.writeFile(fileName, JSON.stringify(data), function(err) {
        if (err) {
          return res.send(500, "Can't Write File");
        } else {
          return res.send(200, "Created");
        }
      });
    } else {
      return res.send(403, "File Already Exists");
    }
  };

  Calendar.prototype.makePath = function(data) {
    return this.dataPath + data._id;
  };

  Calendar.prototype.getScheduleName = function(data) {
    return (data.title + data.start).replace(/[\s\\\/\:\*\?\"\<\>\|\#\{\}\%\&\~]/mg, "");
  };

  return Calendar;

})(Rest);

module.exports = Calendar;
