// Generated by CoffeeScript 1.3.3
var Index, Rest, express,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Rest = require("./rest");

express = require("../node_modules/express");

Index = (function(_super) {

  __extends(Index, _super);

  function Index(appConfig) {
    this.get = __bind(this.get, this);
    Index.__super__.constructor.call(this, "index", appConfig);
    this.route = "/";
  }

  Index.prototype.bind = function(app) {
    Index.__super__.bind.call(this, app);
    return app.use(this.route, express["static"](this.appConfig.paths["public"]));
  };

  Index.prototype.get = function(req, res) {
    return res.render(this.name, {
      title: this.appConfig.name
    });
  };

  return Index;

})(Rest);

module.exports = Index;
