// Generated by CoffeeScript 1.3.3
var Reader, Rest, Upload, express, fs,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Rest = require("./rest");

Reader = require("../helpers/reader");

fs = require("fs");

express = require("../node_modules/express");

Upload = (function(_super) {

  __extends(Upload, _super);

  function Upload(appConfig) {
    this.get = __bind(this.get, this);

    this.post = __bind(this.post, this);
    Upload.__super__.constructor.call(this, "upload", appConfig);
  }

  Upload.prototype.bind = function(app) {
    Upload.__super__.bind.call(this, app);
    return app.use(this.route, express["static"](this.dataPath));
  };

  Upload.prototype.post = function(req, res) {
    var files, saved,
      _this = this;
    files = req.files.files;
    console.log(files);
    if (typeof files.forEach !== 'function') {
      files = [files];
    }
    saved = [];
    files.forEach(function(file) {
      var data, newPath;
      data = fs.readFileSync(file.path);
      console.log("from:" + file.path);
      if (data) {
        newPath = _this.dataPath + file.name;
        fs.writeFileSync(newPath, data);
        return saved.push(_this.name + "/" + file.name);
      }
    });
    return res.send(JSON.stringify(saved));
  };

  Upload.prototype.get = function(req, res) {
    var fileName;
    fileName = req.params.name;
    if (fs.existsSync(fileName)) {
      return res.send(fs.readFileSync(this.dataPath + fileName));
    } else {
      return res.send(404, "Not Found");
    }
  };

  return Upload;

})(Rest);

module.exports = Upload;
